<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Server Information</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 40px;
            background-color: #f9f9f9;
        }
        h1 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            word-break: break-all; /* Prevents long strings from breaking the layout */
        }
        /* Style the key column */
        td:first-child {
            font-weight: bold;
            background-color: #f2f2f2;
            width: 30%;
        }
        /* Style the value column */
        td:last-child {
            background-color: #fff;
        }
    </style>
</head>
<body>

    <h1>Server Environment Details</h1>
    <p>The table below is generated by PHP and shows all the information available in the <code>$_SERVER</code> superglobal array.</p>

    <?php
    echo "<table>";
    foreach ( $_SERVER as $k => $v ) {
        echo "<tr><td>$k</td><td>$v</td></tr>";
    }
    echo "</table>";
    ?>

</body>
</html>