# GitHub Action for deploying to Altervista FTP

name: Deploy to Altervista

on:
  # This action runs every time you push code to the "main" branch
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Sync files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # remote-patch: /htdocs/   # Uncomment and change if your files are not in the root directory